In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df_raw = pd.read_csv('chilean.csv')
df = df_raw.copy()
print("datos importados")

datos importados

In [3]:
display(df.head(35))

print("\n---informacion de nuestro dataser----")
df.info()

print("\n---valores nulos por columna----")
print(df.isnull().sum())

,recipe name,preparation time,min_portion,max_portion,ingredients,steps
0,Ajiaco chileno,40.0,3.0,4.0,"['300 grs de carne asada, puede ser más', '2 c...",['1-Cortamos la carne en tiras y las papas a l...
1,Alfajores chilenos,NaN,20.0,NaN,"['1 1/2 taza de harina cernida', '5 yemas', '1...",['1-Colocar la harina en un bol y añadir las y...
2,NaN,30.0,20.0,NaN,"['125 grs. margarina', '150 grs. azúcar flor (...","['1-Precalentar el horno a 350°F (180°C)', '2-..."
3,Aliño completo,5.0,NaN,NaN,NaN,['1-Idealmente usar un mortero y moler todos l...
4,NaN,NaN,4.0,6.0,['1/2 kilo de carne para la parrilla (lomo vet...,['1-Existe la opción de adobar la carne por un...
5,Arroz con leche,0.0,3.0,NaN,"['1/2 taza de arroz', '2 1/2 tazas de leche lí...",['1-Algunas personas lavan el arroz antes de u...
6,NaN,19.0,4.0,NaN,"['1 pan para sandwich, o marraqueta por person...",NaN
7,Berlines chilenos,45.0,NaN,NaN,['1 sobre de levadura en polvo (7grs/ 2 cuchar...,['1-En un pequeño bol colocar un poquito de ag...
8,Brazo de reina,35.0,8.0,NaN,NaN,NaN
9,Cachitos con manjar,NaN,30.0,NaN,"['500 gr harina sin polvos', '1 pizca de sal',...",['1-Poner la harina en el mesón y formar una c...
10,Calzones rotos,0.0,NaN,NaN,"['3 tazas de harina cernida', '1 cucharada pol...","['1-Unir los ingredientes secos, la harina, lo..."
11,Carbonada de pollo,35.0,4.0,NaN,"['1 cucharada de aceite', '\xa01/2 cebolla', '...",NaN
12,Cazuela de Ave,35.0,2.0,NaN,"['2 trutos de pollo', '4 papas medianas', '2 t...","['1-No es necesario hacer un sofrito, ya que a..."
13,Cazuela de pavo con chuchoca,80.0,4.0,NaN,"['1 cucharada de aceite', '4 presas de pavo', ...",['1-Lavar las presas de pavo y secarlas muy bi...
14,NaN,50.0,4.0,NaN,"['1 1/2 kilo de asado de tira (con hueso)', '4...",NaN
15,"Chacarero, sandwich chileno",14.0,1.0,NaN,"['1 pan para sandwich, puede usar marraqueta, ...",['1-En un sartén con un poquito de aceite o en...
16,Charquicán,50.0,2.0,NaN,NaN,['1-Se pelan las papas y se cortan en cuadrado...
17,Charquicán de cochayuyo,40.0,4.0,NaN,"['1 taza de cochayuyo cocido y picado', '4 pap...",['1-Para el cochayuyo debe dejarlo remojando l...
18,Chilenitos con merengue,NaN,NaN,NaN,"['2 tazas de harina cernida', '1/2 cucharadita...",NaN
19,Chupe de jaibas,0.0,6.0,8.0,"['30 grs de mantequilla', '1 cebolla mediana c...",['1-En un sartén freír a fuego lento junto con...
20,Chupe de locos,42.0,NaN,NaN,"['4 locos grandes o 1 tarro de locos cocidos',...","['1-Si ocupa locos crudos, debe cocinarlos en ..."
21,Pan para sandwich,20.0,12.0,NaN,['1 taza de agua tibia (105°-115°F) (40°-46°C)...,['1-Combinar 1/2 taza de agua tibia con la lev...
22,Cola de mono,20.0,NaN,NaN,"['1 litro de leche líquida', '1 taza de azúcar...",NaN
23,Cocadas y confites,20.0,30.0,NaN,['2 paquetes de galletas bajas en azúcar e ide...,"['1-Moler los dos paquetes de galletas, idealm..."
24,Costillar de cerdo con puré picante,55.0,2.0,NaN,"['1 costillar de cerdo (1 kilo app.)', '1 cuch...",['1-Colocar el costillar en un recipiente y es...
25,NaN,27.0,8.0,NaN,"['1 cebolla pequeña cortada en cuadros', '1/2 ...",NaN
26,Empanadas de camarón queso,0.0,10.0,NaN,"['3 tazas de harina para todo uso, sin polvos ...",['1-En un bol grande colocar la harina y hacer...
27,Empanadas de mariscos,NaN,8.0,NaN,"['PARA LA MASA:', '3 tazas de harina', '70 grs...","['1-Comenzamos con el pino, ya que este para r..."
28,Empanadas de pino al horno,65.0,15.0,NaN,['500 grs de carne de res molida o pequeños tr...,NaN
29,Empanadas de pino,50.0,12.0,NaN,['500 grs carne de vacuno picado o molida (pue...,"['1-Agregue la harina, sal, manteca y el agua ..."
30,Empolvados chilenos,37.0,15.0,NaN,"['5 huevos', '1 taza de harina cernida sin pol...","['1-Precalentar el horno a 350°F (180°C)', '2-..."
31,Ensalada a la chilena,10.0,2.0,NaN,"['3 tomates medianos', '1 cebolla cortada en p...","['1-En esta primera es opcional, pero si no qu..."
32,Ensalada de apio y palta (aguacate),10.0,4.0,NaN,"['Varias ramas de\xa0 apio limpio y picado', '...",NaN
33,Estofado de carne,45.0,NaN,4.0,NaN,['1-En una olla junto con una cucharada de ace...
34,Flan de manjar,80.0,8.0,NaN,"['1 taza de azúcar', '1 tarro de manjar (380 g...","['1-En un sartén colocar un poco de azúcar, cu..."

---informacion de nuestro dataser----
<class 'pandas.DataFrame'>
RangeIndex: 117 entries, 0 to 116
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   recipe name       104 non-null    str
 1   preparation time  99 non-null     float64
 2   min_portion       91 non-null     float64
 3   max_portion       14 non-null     float64
 4   ingredients       104 non-null    str
 5   steps             86 non-null     str
dtypes: float64(3), str(3)
memory usage: 5.6 KB

---valores nulos por columna----
recipe name          13
preparation time     18
min_portion          26
max_portion         103
ingredients          13
steps                31
dtype: int64

In [4]:
#para quitar los separadores en los titulos de las columnas

df.columns = [col.strip().replace(' ', '_') for col in df.columns]

display(df.head())

,recipe_name,preparation_time,min_portion,max_portion,ingredients,steps
0,Ajiaco chileno,40.0,3.0,4.0,"['300 grs de carne asada, puede ser más', '2 c...",['1-Cortamos la carne en tiras y las papas a l...
1,Alfajores chilenos,NaN,20.0,NaN,"['1 1/2 taza de harina cernida', '5 yemas', '1...",['1-Colocar la harina en un bol y añadir las y...
2,NaN,30.0,20.0,NaN,"['125 grs. margarina', '150 grs. azúcar flor (...","['1-Precalentar el horno a 350°F (180°C)', '2-..."
3,Aliño completo,5.0,NaN,NaN,NaN,['1-Idealmente usar un mortero y moler todos l...
4,NaN,NaN,4.0,6.0,['1/2 kilo de carne para la parrilla (lomo vet...,['1-Existe la opción de adobar la carne por un...

In [5]:
#Columna 'recipe_name'
print('Valores nulos es la columna " recipe_name": ', df['recipe_name'].isnull().sum())

df['recipe_name'] = df['recipe_name'].str.capitalize()

df=df.dropna(subset=['recipe_name']) 

display(df.head(10))

Valores nulos es la columna " recipe_name":  13

,recipe_name,preparation_time,min_portion,max_portion,ingredients,steps
0,Ajiaco chileno,40.0,3.0,4.0,"['300 grs de carne asada, puede ser más', '2 c...",['1-Cortamos la carne en tiras y las papas a l...
1,Alfajores chilenos,NaN,20.0,NaN,"['1 1/2 taza de harina cernida', '5 yemas', '1...",['1-Colocar la harina en un bol y añadir las y...
3,Aliño completo,5.0,NaN,NaN,NaN,['1-Idealmente usar un mortero y moler todos l...
5,Arroz con leche,0.0,3.0,NaN,"['1/2 taza de arroz', '2 1/2 tazas de leche lí...",['1-Algunas personas lavan el arroz antes de u...
7,Berlines chilenos,45.0,NaN,NaN,['1 sobre de levadura en polvo (7grs/ 2 cuchar...,['1-En un pequeño bol colocar un poquito de ag...
8,Brazo de reina,35.0,8.0,NaN,NaN,NaN
9,Cachitos con manjar,NaN,30.0,NaN,"['500 gr harina sin polvos', '1 pizca de sal',...",['1-Poner la harina en el mesón y formar una c...
10,Calzones rotos,0.0,NaN,NaN,"['3 tazas de harina cernida', '1 cucharada pol...","['1-Unir los ingredientes secos, la harina, lo..."
11,Carbonada de pollo,35.0,4.0,NaN,"['1 cucharada de aceite', '\xa01/2 cebolla', '...",NaN
12,Cazuela de ave,35.0,2.0,NaN,"['2 trutos de pollo', '4 papas medianas', '2 t...","['1-No es necesario hacer un sofrito, ya que a..."

In [6]:
#Columna 'preparation_time'

print('Valores nulos es la columna "preparation_time": ', df['preparation_time'].isnull().sum())

df['preparation_time'] = pd.to_numeric(df['preparation_time'], errors = 'coerce')

mediana_preptime = df['preparation_time'].median()
df['preparation_time'] = df['preparation_time'].fillna(mediana_preptime, inplace=False)

media_sin_ceros = df[df['preparation_time'] != 0]['preparation_time'].median()

df['preparation_time'] = df['preparation_time'].replace(0, media_sin_ceros)

df['preparation_time'] = df['preparation_time'].astype(int)

display(df.head(10))

Valores nulos es la columna "preparation_time":  16

,recipe_name,preparation_time,min_portion,max_portion,ingredients,steps
0,Ajiaco chileno,40,3.0,4.0,"['300 grs de carne asada, puede ser más', '2 c...",['1-Cortamos la carne en tiras y las papas a l...
1,Alfajores chilenos,35,20.0,NaN,"['1 1/2 taza de harina cernida', '5 yemas', '1...",['1-Colocar la harina en un bol y añadir las y...
3,Aliño completo,5,NaN,NaN,NaN,['1-Idealmente usar un mortero y moler todos l...
5,Arroz con leche,35,3.0,NaN,"['1/2 taza de arroz', '2 1/2 tazas de leche lí...",['1-Algunas personas lavan el arroz antes de u...
7,Berlines chilenos,45,NaN,NaN,['1 sobre de levadura en polvo (7grs/ 2 cuchar...,['1-En un pequeño bol colocar un poquito de ag...
8,Brazo de reina,35,8.0,NaN,NaN,NaN
9,Cachitos con manjar,35,30.0,NaN,"['500 gr harina sin polvos', '1 pizca de sal',...",['1-Poner la harina en el mesón y formar una c...
10,Calzones rotos,35,NaN,NaN,"['3 tazas de harina cernida', '1 cucharada pol...","['1-Unir los ingredientes secos, la harina, lo..."
11,Carbonada de pollo,35,4.0,NaN,"['1 cucharada de aceite', '\xa01/2 cebolla', '...",NaN
12,Cazuela de ave,35,2.0,NaN,"['2 trutos de pollo', '4 papas medianas', '2 t...","['1-No es necesario hacer un sofrito, ya que a..."

In [7]:
#columna 'min_portion'
print('Valores nulos es la columna "min_portion": ', df['min_portion'].isnull().sum())
df['min_portion'] = pd.to_numeric(df['min_portion'], errors = 'coerce')

mediana_min_portion = df['min_portion'].median()
df['min_portion'] = df['min_portion'].fillna(mediana_min_portion, inplace=False)

df['min_portion'] = df['min_portion'].astype(int)

display(df.head(10))

Valores nulos es la columna "min_portion":  25

,recipe_name,preparation_time,min_portion,max_portion,ingredients,steps
0,Ajiaco chileno,40,3,4.0,"['300 grs de carne asada, puede ser más', '2 c...",['1-Cortamos la carne en tiras y las papas a l...
1,Alfajores chilenos,35,20,NaN,"['1 1/2 taza de harina cernida', '5 yemas', '1...",['1-Colocar la harina en un bol y añadir las y...
3,Aliño completo,5,6,NaN,NaN,['1-Idealmente usar un mortero y moler todos l...
5,Arroz con leche,35,3,NaN,"['1/2 taza de arroz', '2 1/2 tazas de leche lí...",['1-Algunas personas lavan el arroz antes de u...
7,Berlines chilenos,45,6,NaN,['1 sobre de levadura en polvo (7grs/ 2 cuchar...,['1-En un pequeño bol colocar un poquito de ag...
8,Brazo de reina,35,8,NaN,NaN,NaN
9,Cachitos con manjar,35,30,NaN,"['500 gr harina sin polvos', '1 pizca de sal',...",['1-Poner la harina en el mesón y formar una c...
10,Calzones rotos,35,6,NaN,"['3 tazas de harina cernida', '1 cucharada pol...","['1-Unir los ingredientes secos, la harina, lo..."
11,Carbonada de pollo,35,4,NaN,"['1 cucharada de aceite', '\xa01/2 cebolla', '...",NaN
12,Cazuela de ave,35,2,NaN,"['2 trutos de pollo', '4 papas medianas', '2 t...","['1-No es necesario hacer un sofrito, ya que a..."

In [8]:

#columna 'max_portion'
print('Valores nulos es la columna "max_portion": ', df['max_portion'].isnull().sum())

df['max_portion'] = pd.to_numeric(df['max_portion'], errors = 'coerce')


df['max_portion'] = df['max_portion'].fillna(df['min_portion'])

df['max_portion'] = df['max_portion'].astype(int)

display(df.head(10))

Valores nulos es la columna "max_portion":  91

,recipe_name,preparation_time,min_portion,max_portion,ingredients,steps
0,Ajiaco chileno,40,3,4,"['300 grs de carne asada, puede ser más', '2 c...",['1-Cortamos la carne en tiras y las papas a l...
1,Alfajores chilenos,35,20,20,"['1 1/2 taza de harina cernida', '5 yemas', '1...",['1-Colocar la harina en un bol y añadir las y...
3,Aliño completo,5,6,6,NaN,['1-Idealmente usar un mortero y moler todos l...
5,Arroz con leche,35,3,3,"['1/2 taza de arroz', '2 1/2 tazas de leche lí...",['1-Algunas personas lavan el arroz antes de u...
7,Berlines chilenos,45,6,6,['1 sobre de levadura en polvo (7grs/ 2 cuchar...,['1-En un pequeño bol colocar un poquito de ag...
8,Brazo de reina,35,8,8,NaN,NaN
9,Cachitos con manjar,35,30,30,"['500 gr harina sin polvos', '1 pizca de sal',...",['1-Poner la harina en el mesón y formar una c...
10,Calzones rotos,35,6,6,"['3 tazas de harina cernida', '1 cucharada pol...","['1-Unir los ingredientes secos, la harina, lo..."
11,Carbonada de pollo,35,4,4,"['1 cucharada de aceite', '\xa01/2 cebolla', '...",NaN
12,Cazuela de ave,35,2,2,"['2 trutos de pollo', '4 papas medianas', '2 t...","['1-No es necesario hacer un sofrito, ya que a..."

In [10]:
#columna 'ingridients'
print('Valores nulos es la columna "ingridients": ', df['ingredients'].isnull().sum())

df = df.dropna(subset=['ingredients'])

df['ingredients'] = df['ingredients'].str.capitalize()

df['ingredients'] = df['ingredients'].str.replace(r"[\[\]\"']", '', regex=True)

display(df.head(10))

Valores nulos es la columna "ingridients":  0

,recipe_name,preparation_time,min_portion,max_portion,ingredients,steps
0,Ajiaco chileno,40,3,4,"300 grs de carne asada, puede ser más, 2 cucha...",['1-Cortamos la carne en tiras y las papas a l...
1,Alfajores chilenos,35,20,20,"1 1/2 taza de harina cernida, 5 yemas, 1 cucha...",['1-Colocar la harina en un bol y añadir las y...
5,Arroz con leche,35,3,3,"1/2 taza de arroz, 2 1/2 tazas de leche líquid...",['1-Algunas personas lavan el arroz antes de u...
7,Berlines chilenos,45,6,6,1 sobre de levadura en polvo (7grs/ 2 cucharad...,['1-En un pequeño bol colocar un poquito de ag...
9,Cachitos con manjar,35,30,30,"500 gr harina sin polvos, 1 pizca de sal, 8 ye...",['1-Poner la harina en el mesón y formar una c...
10,Calzones rotos,35,6,6,"3 tazas de harina cernida, 1 cucharada polvos ...","['1-Unir los ingredientes secos, la harina, lo..."
11,Carbonada de pollo,35,4,4,"1 cucharada de aceite, \xa01/2 cebolla, 1 pech...",NaN
12,Cazuela de ave,35,2,2,"2 trutos de pollo, 4 papas medianas, 2 trozos ...","['1-No es necesario hacer un sofrito, ya que a..."
13,Cazuela de pavo con chuchoca,80,4,4,"1 cucharada de aceite, 4 presas de pavo, 1/2 c...",['1-Lavar las presas de pavo y secarlas muy bi...
15,"Chacarero, sandwich chileno",14,1,1,"1 pan para sandwich, puede usar marraqueta, pa...",['1-En un sartén con un poquito de aceite o en...

In [11]:
#columna 'steps'
print('Valores nulos es la columna "steps": ', df['steps'].isnull().sum())

df = df.dropna(subset=['steps'])

df['steps'] = df['steps'].str.capitalize()

df['steps'] = df['steps'].str.replace(r"[\[\]\"']", '', regex=True)

display(df.head(10))

Valores nulos es la columna "steps":  23

,recipe_name,preparation_time,min_portion,max_portion,ingredients,steps
0,Ajiaco chileno,40,3,4,"300 grs de carne asada, puede ser más, 2 cucha...",1-cortamos la carne en tiras y las papas a lo ...
1,Alfajores chilenos,35,20,20,"1 1/2 taza de harina cernida, 5 yemas, 1 cucha...",1-colocar la harina en un bol y añadir las yem...
5,Arroz con leche,35,3,3,"1/2 taza de arroz, 2 1/2 tazas de leche líquid...",1-algunas personas lavan el arroz antes de usa...
7,Berlines chilenos,45,6,6,1 sobre de levadura en polvo (7grs/ 2 cucharad...,1-en un pequeño bol colocar un poquito de agua...
9,Cachitos con manjar,35,30,30,"500 gr harina sin polvos, 1 pizca de sal, 8 ye...",1-poner la harina en el mesón y formar una cor...
10,Calzones rotos,35,6,6,"3 tazas de harina cernida, 1 cucharada polvos ...","1-unir los ingredientes secos, la harina, los ..."
12,Cazuela de ave,35,2,2,"2 trutos de pollo, 4 papas medianas, 2 trozos ...","1-no es necesario hacer un sofrito, ya que al ..."
13,Cazuela de pavo con chuchoca,80,4,4,"1 cucharada de aceite, 4 presas de pavo, 1/2 c...",1-lavar las presas de pavo y secarlas muy bien...
15,"Chacarero, sandwich chileno",14,1,1,"1 pan para sandwich, puede usar marraqueta, pa...",1-en un sartén con un poquito de aceite o en u...
17,Charquicán de cochayuyo,40,4,4,"1 taza de cochayuyo cocido y picado, 4 papas g...",1-para el cochayuyo debe dejarlo remojando la ...

In [12]:
#new column ingredient count
#gracias a apply recorreremos la columna ingredientes y junto a la funcion lambda 
#contara las comas y las determinara como un ingrediente
df['ingredient_count'] = df['ingredients'].apply(lambda x: len(str(x).split(',')) if pd.notnull(x) else 0)

display(df.head(10))

,recipe_name,preparation_time,min_portion,max_portion,ingredients,steps,ingredient_count
0,Ajiaco chileno,40,3,4,"300 grs de carne asada, puede ser más, 2 cucha...",1-cortamos la carne en tiras y las papas a lo ...,15
1,Alfajores chilenos,35,20,20,"1 1/2 taza de harina cernida, 5 yemas, 1 cucha...",1-colocar la harina en un bol y añadir las yem...,4
5,Arroz con leche,35,3,3,"1/2 taza de arroz, 2 1/2 tazas de leche líquid...",1-algunas personas lavan el arroz antes de usa...,5
7,Berlines chilenos,45,6,6,1 sobre de levadura en polvo (7grs/ 2 cucharad...,1-en un pequeño bol colocar un poquito de agua...,14
9,Cachitos con manjar,35,30,30,"500 gr harina sin polvos, 1 pizca de sal, 8 ye...",1-poner la harina en el mesón y formar una cor...,7
10,Calzones rotos,35,6,6,"3 tazas de harina cernida, 1 cucharada polvos ...","1-unir los ingredientes secos, la harina, los ...",10
12,Cazuela de ave,35,2,2,"2 trutos de pollo, 4 papas medianas, 2 trozos ...","1-no es necesario hacer un sofrito, ya que al ...",16
13,Cazuela de pavo con chuchoca,80,4,4,"1 cucharada de aceite, 4 presas de pavo, 1/2 c...",1-lavar las presas de pavo y secarlas muy bien...,16
15,"Chacarero, sandwich chileno",14,1,1,"1 pan para sandwich, puede usar marraqueta, pa...",1-en un sartén con un poquito de aceite o en u...,9
17,Charquicán de cochayuyo,40,4,4,"1 taza de cochayuyo cocido y picado, 4 papas g...",1-para el cochayuyo debe dejarlo remojando la ...,14

In [13]:
#new column nivel de dificultad por tiempo

def categorizar_tiempo(tiempo):
    if tiempo <= 20:
        return 'duracion Rapida'
    elif tiempo <= 60:
        return 'duracion Media '
    else:
        return 'duracion Larga'

df['duration_level'] = df['preparation_time'].apply(categorizar_tiempo)

display(df.head(10))

,recipe_name,preparation_time,min_portion,max_portion,ingredients,steps,ingredient_count,duration_level
0,Ajiaco chileno,40,3,4,"300 grs de carne asada, puede ser más, 2 cucha...",1-cortamos la carne en tiras y las papas a lo ...,15,duracion Media
1,Alfajores chilenos,35,20,20,"1 1/2 taza de harina cernida, 5 yemas, 1 cucha...",1-colocar la harina en un bol y añadir las yem...,4,duracion Media
5,Arroz con leche,35,3,3,"1/2 taza de arroz, 2 1/2 tazas de leche líquid...",1-algunas personas lavan el arroz antes de usa...,5,duracion Media
7,Berlines chilenos,45,6,6,1 sobre de levadura en polvo (7grs/ 2 cucharad...,1-en un pequeño bol colocar un poquito de agua...,14,duracion Media
9,Cachitos con manjar,35,30,30,"500 gr harina sin polvos, 1 pizca de sal, 8 ye...",1-poner la harina en el mesón y formar una cor...,7,duracion Media
10,Calzones rotos,35,6,6,"3 tazas de harina cernida, 1 cucharada polvos ...","1-unir los ingredientes secos, la harina, los ...",10,duracion Media
12,Cazuela de ave,35,2,2,"2 trutos de pollo, 4 papas medianas, 2 trozos ...","1-no es necesario hacer un sofrito, ya que al ...",16,duracion Media
13,Cazuela de pavo con chuchoca,80,4,4,"1 cucharada de aceite, 4 presas de pavo, 1/2 c...",1-lavar las presas de pavo y secarlas muy bien...,16,duracion Larga
15,"Chacarero, sandwich chileno",14,1,1,"1 pan para sandwich, puede usar marraqueta, pa...",1-en un sartén con un poquito de aceite o en u...,9,duracion Rapida
17,Charquicán de cochayuyo,40,4,4,"1 taza de cochayuyo cocido y picado, 4 papas g...",1-para el cochayuyo debe dejarlo remojando la ...,14,duracion Media

In [14]:
#new column, nivel de complejidad de receta

max_time = df['preparation_time'].max()
max_ing = df['ingredient_count'].max()

df['complexity_score'] = ((df['preparation_time'] / max_time) * 50) + ((df['ingredient_count'] / max_ing) * 50)

display(df.head(10))

,recipe_name,preparation_time,min_portion,max_portion,ingredients,steps,ingredient_count,duration_level,complexity_score
0,Ajiaco chileno,40,3,4,"300 grs de carne asada, puede ser más, 2 cucha...",1-cortamos la carne en tiras y las papas a lo ...,15,duracion Media,53.698752
1,Alfajores chilenos,35,20,20,"1 1/2 taza de harina cernida, 5 yemas, 1 cucha...",1-colocar la harina en un bol y añadir las yem...,4,duracion Media,26.247772
5,Arroz con leche,35,3,3,"1/2 taza de arroz, 2 1/2 tazas de leche líquid...",1-algunas personas lavan el arroz antes de usa...,5,duracion Media,28.520499
7,Berlines chilenos,45,6,6,1 sobre de levadura en polvo (7grs/ 2 cucharad...,1-en un pequeño bol colocar un poquito de agua...,14,duracion Media,53.877005
9,Cachitos con manjar,35,30,30,"500 gr harina sin polvos, 1 pizca de sal, 8 ye...",1-poner la harina en el mesón y formar una cor...,7,duracion Media,33.065954
10,Calzones rotos,35,6,6,"3 tazas de harina cernida, 1 cucharada polvos ...","1-unir los ingredientes secos, la harina, los ...",10,duracion Media,39.884135
12,Cazuela de ave,35,2,2,"2 trutos de pollo, 4 papas medianas, 2 trozos ...","1-no es necesario hacer un sofrito, ya que al ...",16,duracion Media,53.520499
13,Cazuela de pavo con chuchoca,80,4,4,"1 cucharada de aceite, 4 presas de pavo, 1/2 c...",1-lavar las presas de pavo y secarlas muy bien...,16,duracion Larga,75.579323
15,"Chacarero, sandwich chileno",14,1,1,"1 pan para sandwich, puede usar marraqueta, pa...",1-en un sartén con un poquito de aceite o en u...,9,duracion Rapida,27.317291
17,Charquicán de cochayuyo,40,4,4,"1 taza de cochayuyo cocido y picado, 4 papas g...",1-para el cochayuyo debe dejarlo remojando la ...,14,duracion Media,51.426025

In [15]:
#exportar
df.to_csv('datos_limpios.csv', index=False,encoding='utf-8')
df.to_excel('datos_limpios.xlsx')